# Intrusion Detection System using Machine Learning

## Problem Statement
The goal is to classify network traffic as normal or attack using the NSL-KDD dataset.

In [15]:
import pandas as pd

# Load dataset (make sure you uploaded files)
train = pd.read_csv("KDDTrain+.txt", header=None)
test = pd.read_csv("KDDTest+.txt", header=None)

train.head()

,0,1,2,3,4,5,6,7,8,9,...,33,34,35,36,37,38,39,40,41,42
0,0,tcp,ftp_data,SF,491,0,0,0,0,0,...,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,normal,20.0
1,0,udp,other,SF,146,0,0,0,0,0,...,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,normal,15.0
2,0,tcp,private,S0,0,0,0,0,0,0,...,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,neptune,19.0
3,0,tcp,http,SF,232,8153,0,0,0,0,...,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,normal,21.0
4,0,tcp,http,SF,199,420,0,0,0,0,...,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,normal,21.0

In [16]:
columns = [
    "duration","protocol_type","service","flag","src_bytes","dst_bytes","land",
    "wrong_fragment","urgent","hot","num_failed_logins","logged_in",
    "num_compromised","root_shell","su_attempted","num_root","num_file_creations",
    "num_shells","num_access_files","num_outbound_cmds","is_host_login",
    "is_guest_login","count","srv_count","serror_rate","srv_serror_rate",
    "rerror_rate","srv_rerror_rate","same_srv_rate","diff_srv_rate",
    "srv_diff_host_rate","dst_host_count","dst_host_srv_count",
    "dst_host_same_srv_rate","dst_host_diff_srv_rate",
    "dst_host_same_src_port_rate","dst_host_srv_diff_host_rate",
    "dst_host_serror_rate","dst_host_srv_serror_rate",
    "dst_host_rerror_rate","dst_host_srv_rerror_rate",
    "label","difficulty"
]

train.columns = columns
test.columns = columns

# Drop difficulty column
train = train.drop("difficulty", axis=1)
test = test.drop("difficulty", axis=1)

train.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,label
0,0,tcp,ftp_data,SF,491,0,0,0,0,0,...,25.0,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,normal
1,0,udp,other,SF,146,0,0,0,0,0,...,1.0,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,normal
2,0,tcp,private,S0,0,0,0,0,0,0,...,26.0,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,neptune
3,0,tcp,http,SF,232,8153,0,0,0,0,...,255.0,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,normal
4,0,tcp,http,SF,199,420,0,0,0,0,...,255.0,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,normal

In [17]:
train['label'] = train['label'].astype(str)
test['label'] = test['label'].astype(str)

train['label'] = train['label'].apply(lambda x: 0 if 'normal' in x else 1)
test['label'] = test['label'].apply(lambda x: 0 if 'normal' in x else 1)

train['label'].value_counts()

label
0    40533
1    35502
Name: count, dtype: int64

In [18]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd

cols = ['protocol_type', 'service', 'flag']

for col in cols:
    train[col] = train[col].astype(str)
    test[col] = test[col].astype(str)

    le = LabelEncoder()
    combined = pd.concat([train[col], test[col]])
    le.fit(combined)

    train[col] = le.transform(train[col])
    test[col] = le.transform(test[col])

train.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,label
0,0,1,20,9,491,0,0,0,0,0,...,25.0,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,0
1,0,2,43,9,146,0,0,0,0,0,...,1.0,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,0
2,0,1,48,5,0,0,0,0,0,0,...,26.0,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,1
3,0,1,23,9,232,8153,0,0,0,0,...,255.0,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,0
4,0,1,23,9,199,420,0,0,0,0,...,255.0,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0

In [19]:
X_train = train.drop('label', axis=1)
y_train = train['label']

X_test = test.drop('label', axis=1)
y_test = test['label']

In [20]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [21]:
import pandas as pd

X_train = pd.DataFrame(X_train)
X_test = pd.DataFrame(X_test)

X_train = X_train.dropna()
y_train = y_train[X_train.index]

X_test = X_test.dropna()
y_test = y_test[X_test.index]

X_train = X_train.values
X_test = X_test.values

# Check NaN
print(pd.DataFrame(X_train).isnull().sum().sum())

0

In [22]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

model = LogisticRegression(max_iter=2000)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Logistic Regression:")
print(classification_report(y_test, y_pred))

Logistic Regression:
              precision    recall  f1-score   support

           0       0.65      0.93      0.77      9711
           1       0.93      0.62      0.74     12833

    accuracy                           0.76     22544
   macro avg       0.79      0.78      0.76     22544
weighted avg       0.81      0.76      0.75     22544

In [23]:
model_bal = LogisticRegression(max_iter=2000, class_weight={0:1, 1:2})
model_bal.fit(X_train, y_train)

y_pred_bal = model_bal.predict(X_test)

print("Balanced Logistic Regression:")
print(classification_report(y_test, y_pred_bal))

Balanced Logistic Regression:
              precision    recall  f1-score   support

           0       0.66      0.93      0.77      9711
           1       0.92      0.64      0.76     12833

    accuracy                           0.76     22544
   macro avg       0.79      0.78      0.76     22544
weighted avg       0.81      0.76      0.76     22544

In [24]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()
rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

print("Random Forest:")
print(classification_report(y_test, y_pred_rf))

Random Forest:
              precision    recall  f1-score   support

           0       0.66      0.97      0.79      9711
           1       0.97      0.62      0.76     12833

    accuracy                           0.77     22544
   macro avg       0.81      0.80      0.77     22544
weighted avg       0.84      0.77      0.77     22544

## Results Interpretation

- Logistic Regression provides a strong baseline model.
- Balanced model improves recall (detects more attacks).
- Random Forest generally performs better due to non-linear learning.

### Key Insight:
In intrusion detection, **recall is more important than precision** because missing an attack is more dangerous than a false alarm.

## Conclusion

This project demonstrates how machine learning can be applied to detect network intrusions.

- Data preprocessing and encoding are critical steps
- Model choice affects precision vs recall tradeoff
- Random Forest shows strong performance

Future improvements:
- Use XGBoost
- Deploy as real-time system